# Generated by Django 5.2.7 on 2025-10-21 09:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('Available', 'Available'), ('For Sale', 'For Sale')], max_length=20)),
                ('category_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Property', 'Property')], max_length=20)),
                ('images', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('bathroom', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('bedroom', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('Available', 'Available'), ('For Sale', 'For Sale')], max_length=20)),
                ('category_type', models.CharField(choices=[('Apartment', 'Apartment'), ('land', 'land')], max_length=20)),
                ('images', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('Available', 'Available'), ('For Sale', 'For Sale')], max_length=20)),
                ('category_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Property', 'Property')], max_length=20)),
                ('images', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('bathroom', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('bedroom', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('Available', 'Available'), ('For Sale', 'For Sale')], max_length=20)),
                ('category_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Property', 'Property')], max_length=20)),
                ('images', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('bathroom', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('bedroom', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='shortlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('Available', 'Available'), ('For Sale', 'For Sale')], max_length=20)),
                ('category_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Property', 'Property')], max_length=20)),
                ('images', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('bathroom', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('bedroom', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
